// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectBackend.Migrations
{
    [DbContext(typeof(MvcWordAssetsContext))]
    [Migration("20230913091136_CreateModel3DData")]
    partial class CreateModel3DData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ProjectBackend.Models.Model3DData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkDownload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Model3DData");
                });

            modelBuilder.Entity("ProjectBackend.Models.Model3DData+Mode3DBehaviorData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Audio")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Model3DDataID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Thumb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Model3DDataID");

                    b.ToTable("Mode3DBehaviorData");
                });

            modelBuilder.Entity("ProjectBackend.Models.WordAssets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkDownLoad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WordAssets");
                });

            modelBuilder.Entity("ProjectBackend.Models.Model3DData+Mode3DBehaviorData", b =>
                {
                    b.HasOne("ProjectBackend.Models.Model3DData", "Model3DData")
                        .WithMany("Behavior")
                        .HasForeignKey("Model3DDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model3DData");
                });

            modelBuilder.Entity("ProjectBackend.Models.Model3DData", b =>
                {
                    b.Navigation("Behavior");
                });
#pragma warning restore 612, 618
        }
    }
}
